const cfg=window.ICA_CONFIG,sb=supabase.createClient(cfg.supabaseUrl,cfg.supabaseKey),fnBase=cfg.supabaseUrl+"/functions/v1/ica-application-upload";let session=null,appId=null,appNo=null;
const $=s=>document.querySelector(s), state=$("#authState"), form=$("#applyForm"), submit=$("#submitBtn");
const fees={1:70000,2:80000,3:90000,4:100000,5:120000,6:150000,7:200000,8:250000,9:300000};
const faNum=n=>Number(n).toLocaleString("fa-IR"), money=n=>"₩"+Number(n).toLocaleString("en-US")+" KRW";
const feeGrid=$("#feeGrid"),danPriceSelect=$("#danPriceSelect"),danPrice=$("#danPrice"),requestedRank=$("#requestedRank"),currentRank=$("#currentRank");
Object.entries(fees).forEach(([d,p])=>{feeGrid.insertAdjacentHTML("beforeend",'<div class="fee"><b>Dan '+d+'</b><br>'+money(p)+'</div>');danPriceSelect.insertAdjacentHTML("beforeend",'<option value="'+d+'">Dan '+d+' · '+money(p)+'</option>');requestedRank.insertAdjacentHTML("beforeend",'<option value="'+d+' DAN">Dan '+d+' · '+money(p)+'</option>');currentRank.insertAdjacentHTML("beforeend",'<option value="'+d+' DAN">Dan '+d+'</option>')});
function showPrice(d){danPrice.textContent=money(fees[d]);danPriceSelect.value=d;requestedRank.value=d+" DAN"}
danPriceSelect.addEventListener("change",()=>showPrice(danPriceSelect.value));requestedRank.addEventListener("change",()=>{const d=parseInt(requestedRank.value);if(d)showPrice(d)});showPrice(1);
async function sync(){const {data}=await sb.auth.getSession();session=data.session||null;if(session?.user?.email){state.textContent="E-mail vérifié : "+session.user.email;$("#applyEmail").value=session.user.email;$("#loginEmail").value=session.user.email;submit.disabled=false}else{state.textContent="Veuillez d’abord vérifier votre e-mail.";submit.disabled=true}}
$("#magicBtn").onclick=async()=>{const email=$("#loginEmail").value.trim();if(!email)return;state.textContent="Envoi…";const {error}=await sb.auth.signInWithOtp({email,options:{emailRedirectTo:location.href.split("#")[0]}});state.textContent=error?("Erreur : "+error.message):"Le lien de connexion a été envoyé. Ouvrez-le puis revenez sur cette page."};
form.onsubmit=async e=>{e.preventDefault();await sync();if(!session)return;const fd=new FormData(form),data=Object.fromEntries(fd.entries());data.country_code="MA";data.preferred_language="fr";data.email=session.user.email;if(data.application_type==="DAN"){data.issuer_code="WTKF";const d=parseInt(data.requested_rank);data.qualification_name="WTKF International Dan · "+data.requested_rank+" · Official fee "+money(fees[d])}submit.disabled=true;$("#submitState").textContent="Enregistrement…";const {data:r,error}=await sb.rpc("ica_submit_global_application",{p_data:data});if(error){$("#submitState").textContent="Erreur : "+error.message;submit.disabled=false;return}appId=r.id;appNo=r.application_no;$("#submitState").textContent="Demande enregistrée avec succès.";$("#filesCard").style.display="block";$("#appNo").textContent="Numéro de demande : "+appNo};
document.querySelectorAll('input[type="file"][data-kind]').forEach(inp=>inp.onchange=async()=>{const file=inp.files?.[0];if(!file||!appId||!session)return;if(file.size>5242880){$("#uploadState").textContent="Taille maximale : 5 Mo.";inp.value="";return}const ext=(file.name.split(".").pop()||"").toLowerCase();$("#uploadState").textContent="Téléversement…";const res=await fetch(fnBase,{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+session.access_token,"apikey":cfg.supabaseKey},body:JSON.stringify({application_id:appId,kind:inp.dataset.kind,content_type:file.type,extension:ext})});const signed=await res.json();if(!res.ok){$("#uploadState").textContent="Erreur de préparation du téléversement.";return}const {error}=await sb.storage.from("ica-application-evidence").uploadToSignedUrl(signed.path,signed.token,file,{contentType:file.type});$("#uploadState").textContent=error?"Erreur lors du téléversement.":"Fichier téléversé avec succès."});
sb.auth.onAuthStateChange(()=>sync());sync();