const db=window.supabase.createClient(ICA_CONFIG.supabaseUrl,ICA_CONFIG.supabaseKey),form=document.getElementById('verifyForm'),box=document.getElementById('result'),input=document.getElementById('credentialNo');
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function field(label,value){return value?`<div class="field"><small>${label}</small><b>${esc(value)}</b></div>`:''}
function kind(d){const text=`${d.detail_name||''} ${d.type_name||''} ${d.position_title||''}`.toLowerCase();if(/branch|지부/.test(text))return'BRANCH';if(d.position_title||/appointment|임명/.test(text))return'APPOINTMENT';if(/institution|organization|기관|인증기관/.test(text))return'ORGANIZATION';return'CREDENTIAL'}
function statusLabel(d,k){const s=String(d.status||'VALID').toUpperCase();if(s!=='VALID')return s;if(k==='APPOINTMENT')return'ACTIVE';if(k==='BRANCH')return'REGISTERED';if(k==='ORGANIZATION')return'ACCREDITED';return'VALID'}
function titleFor(k){return({CREDENTIAL:'OFFICIAL CREDENTIAL RECORD',APPOINTMENT:'OFFICIAL APPOINTMENT RECORD',BRANCH:'OFFICIAL BRANCH RECORD',ORGANIZATION:'OFFICIAL ORGANIZATION RECORD'})[k]}
function imageFor(d){const src=d.photo_url||'../assets/%20images/ica-official-emblem..png';return`<div class="portrait ${d.photo_url?'person':'fallback'}"><img src="${esc(src)}" alt="Official record image" onerror="this.src='../assets/%20images/ica-official-emblem..png';this.parentElement.classList.add('fallback')"></div>`}
function shareUrl(no){const u=new URL(location.href);u.searchParams.set('code',no);return u.toString()}
async function copyLink(no){try{await navigator.clipboard.writeText(shareUrl(no));alert('ICA 공식 조회 링크를 복사했습니다.')}catch{prompt('조회 링크를 복사하세요.',shareUrl(no))}}
async function shareRecord(no){const url=shareUrl(no);if(navigator.share){try{await navigator.share({title:'ICA VERIFIED · '+no,text:'ICA Official Verification Record',url})}catch{}}else copyLink(no)}
function render(d){const k=kind(d),s=statusLabel(d,k),name=d.person_name_en||d.person_name||d.qualification_name||d.issuer_name||'ICA OFFICIAL RECORD';const subtitle=d.position_title||d.qualification_name||d.rank_grade||d.detail_name||d.type_name||'';box.innerHTML=`<article class="credential-card"><div class="verified-head"><div><span class="verified-check">✓</span><b>ICA VERIFIED</b><small>${titleFor(k)}</small></div><strong class="record-status ${esc(d.status)}">${esc(s)}</strong></div><div class="identity">${imageFor(d)}<div class="identity-copy"><p class="record-type">${esc(k)}</p><h3>${esc(name)}</h3>${d.person_name&&d.person_name!==name?`<p class="local-name">${esc(d.person_name)}</p>`:''}${subtitle?`<h4>${esc(subtitle)}</h4>`:''}<p class="record-no">${esc(d.credential_no)}</p></div></div><div class="fields">${field('Issuing Organization · 발급기관',d.issuer_name)}${field('Credential Type · 종류',d.detail_name||d.type_name)}${field('Name · 성명',d.person_name)}${field('English Name · 영문명',d.person_name_en)}${field('Qualification / Position · 자격·직책',d.qualification_name||d.position_title)}${field('Discipline · 종목',d.discipline)}${field('Rank / Grade · 단·등급',d.rank_grade)}${field('Issued · 발급일',d.issued_on)}${field('Valid Until · 유효기간',d.valid_until)}</div><div class="official-seal"><img src="../assets/%20images/ica-official-emblem..png" alt="ICA"><div><small>REGISTERED & VERIFIED BY</small><b>ICA · INTERNATIONAL CREDENTIAL ALLIANCE</b><span>This screen is an official public verification record.</span></div></div><div class="record-actions"><button onclick="copyLink('${esc(d.credential_no)}')">COPY LINK</button><button onclick="shareRecord('${esc(d.credential_no)}')">SHARE</button><button onclick="window.print()">PRINT</button></div></article>`}
async function verify(no){no=String(no||'').trim().toUpperCase();if(!no)return;box.classList.remove('hidden');box.innerHTML='<p class="checking">ICA Global Registry를 확인하고 있습니다…</p>';const{data,error}=await db.rpc('ica_verify_credential',{p_credential_no:no});if(error||!data){box.innerHTML=`<div class="not-found"><strong>NOT FOUND</strong><b>ICA GLOBAL REGISTRY</b><p>발급번호를 다시 확인해 주세요.</p></div>`;return}render(data)}
form.addEventListener('submit',e=>{e.preventDefault();verify(input.value)});const qs=new URLSearchParams(location.search),q=qs.get('code')||qs.get('no');if(q){input.value=q;verify(q)}
window.copyLink=copyLink;window.shareRecord=shareRecord;