-- ICA GLOBAL CREDENTIAL SYSTEM v1.0
-- Legacy source public.gms_legacy_members is intentionally read-only and unchanged.

create schema if not exists private;

create or replace function private.ica_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public, auth, pg_temp
as $$
  select exists (
    select 1
    from public.gms_admin_accounts a
    where a.auth_user_id = auth.uid()
      and a.is_active = true
      and a.role in ('founder','master','coadmin','admin')
  );
$$;
revoke all on function private.ica_is_admin() from public;
grant usage on schema private to authenticated;
grant execute on function private.ica_is_admin() to authenticated;

create table if not exists public.ica_issuers (
  id uuid primary key default gen_random_uuid(),
  code text not null unique check (code ~ '^[A-Z0-9]{2,12}$'),
  name_ko text not null,
  name_en text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ica_credential_types (
  id uuid primary key default gen_random_uuid(),
  code text not null unique check (code ~ '^[A-Z]{3}$'),
  name_ko text not null,
  name_en text,
  default_card boolean not null default true,
  default_document boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ica_detail_types (
  id uuid primary key default gen_random_uuid(),
  credential_type_id uuid not null references public.ica_credential_types(id),
  issuer_id uuid references public.ica_issuers(id),
  code text,
  name_ko text not null,
  name_en text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (credential_type_id, issuer_id, name_ko)
);

create table if not exists public.ica_number_rules (
  id uuid primary key default gen_random_uuid(),
  issuer_id uuid not null references public.ica_issuers(id),
  credential_type_id uuid not null references public.ica_credential_types(id),
  prefix text not null,
  separator text not null default '-',
  next_value bigint not null check (next_value > 0),
  digits smallint not null default 6 check (digits between 1 and 18),
  is_legacy_continuation boolean not null default false,
  is_active boolean not null default true,
  updated_at timestamptz not null default now(),
  unique (issuer_id, credential_type_id)
);

create table if not exists public.ica_credentials (
  id uuid primary key default gen_random_uuid(),
  credential_no text not null unique,
  issuer_id uuid not null references public.ica_issuers(id),
  credential_type_id uuid not null references public.ica_credential_types(id),
  detail_type_id uuid references public.ica_detail_types(id),
  detail_label text,
  person_name text not null,
  person_name_en text,
  photo_url text,
  qualification_name text,
  discipline text,
  rank_grade text,
  position_title text,
  issued_on date not null default current_date,
  valid_until date,
  phone text,
  email text,
  postal_code text,
  address text,
  address_detail text,
  admin_note text,
  status text not null default 'VALID' check (status in ('VALID','EXPIRED','SUSPENDED','REVOKED')),
  card_requested boolean not null default true,
  document_requested boolean not null default false,
  created_by uuid not null default auth.uid() references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ica_credentials_issuer_idx on public.ica_credentials(issuer_id);
create index if not exists ica_credentials_type_idx on public.ica_credentials(credential_type_id);
create index if not exists ica_credentials_person_idx on public.ica_credentials(person_name);

create table if not exists public.ica_status_history (
  id bigint generated by default as identity primary key,
  credential_id uuid not null references public.ica_credentials(id) on delete cascade,
  old_status text,
  new_status text not null check (new_status in ('VALID','EXPIRED','SUSPENDED','REVOKED')),
  reason text,
  changed_by uuid not null default auth.uid() references auth.users(id),
  changed_at timestamptz not null default now()
);

create table if not exists public.ica_reissues (
  id bigint generated by default as identity primary key,
  credential_id uuid not null references public.ica_credentials(id) on delete cascade,
  reason text not null,
  reissued_on date not null default current_date,
  processed_by uuid not null default auth.uid() references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.ica_shipments (
  id uuid primary key default gen_random_uuid(),
  credential_id uuid not null unique references public.ica_credentials(id) on delete cascade,
  fulfillment_status text not null default 'REGISTERED' check (fulfillment_status in ('REGISTERED','CARD_PRINTED','DOCUMENT_PRINTED','PACKED','SHIPPED')),
  recipient_name text not null,
  recipient_phone text,
  postal_code text,
  address text,
  address_detail text,
  shipping_method text,
  tracking_number text,
  shipped_on date,
  shipping_cost integer check (shipping_cost is null or shipping_cost >= 0),
  note text,
  updated_by uuid not null default auth.uid() references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ica_print_templates (
  id uuid primary key default gen_random_uuid(),
  template_code text not null unique,
  template_kind text not null check (template_kind in ('CARD','DOCUMENT')),
  name text not null,
  issuer_id uuid references public.ica_issuers(id),
  credential_type_id uuid references public.ica_credential_types(id),
  config jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.ica_issuers(code,name_ko,name_en) values
 ('IPMA','국제경찰무도연합회','International Police Martial Arts Association'),
 ('WTKF','세계태권검도연맹','World TaekwonKumdo Federation'),
 ('IDP','국제드론순찰대','International Drone Patrol'),
 ('ACTS','ACTS 선교연합','ACTS Mission Alliance'),
 ('GN24','GLOBAL NEWS24','GLOBAL NEWS24'),
 ('ICA','국제자격관리본부','International Credential Alliance')
on conflict (code) do update set name_ko=excluded.name_ko,name_en=excluded.name_en;

insert into public.ica_credential_types(code,name_ko,name_en,default_card,default_document) values
 ('DAN','단증','Dan Certificate',true,true),
 ('LIC','자격증·지도자 자격증','License / Instructor Certificate',true,true),
 ('MEM','대원증·회원증','Member Credential',true,false),
 ('PRS','기자증','Press Credential',true,false),
 ('OFF','임원증·직책증','Officer Credential',true,false),
 ('APT','임명','Appointment',true,true),
 ('COM','위촉','Commission',true,true),
 ('CER','과정 인증·교육 인증·수료','Course / Education Certificate',false,true),
 ('ORG','기관·지부·교육기관 인증','Organization Accreditation',false,true)
on conflict (code) do update set name_ko=excluded.name_ko,name_en=excluded.name_en,
 default_card=excluded.default_card,default_document=excluded.default_document;

insert into public.ica_detail_types(credential_type_id,issuer_id,code,name_ko,name_en)
select t.id,i.id,v.code,v.name_ko,v.name_en
from (values
 ('LIC','IPMA','POLICE-INSTRUCTOR','경찰무도 지도자','Police Martial Arts Instructor'),
 ('LIC','IPMA','SECURITY-INSTRUCTOR','경호무술 지도자','Security Martial Arts Instructor'),
 ('LIC','WTKF','TKK-INSTRUCTOR','태권검도 지도자','TaekwonKumdo Instructor'),
 ('MEM','IDP','IDP-MEMBER','국제드론순찰대 대원','IDP Member'),
 ('MEM','IDP','CHILD-PATROL','어린이순찰대 대원','Child Patrol Member'),
 ('MEM','IDP','YOUTH-PATROL','청소년순찰대 대원','Youth Patrol Member'),
 ('PRS','GN24','REPORTER','기자','Reporter'),
 ('PRS','GN24','PHOTO-REPORTER','사진기자','Photo Reporter'),
 ('PRS','GN24','CHILD-REPORTER','어린이기자','Child Reporter'),
 ('PRS','GN24','YOUTH-REPORTER','청소년기자','Youth Reporter')
) v(type_code,issuer_code,code,name_ko,name_en)
join public.ica_credential_types t on t.code=v.type_code
join public.ica_issuers i on i.code=v.issuer_code
on conflict (credential_type_id,issuer_id,name_ko) do update set code=excluded.code,name_en=excluded.name_en;

-- Exact continuation of the most recent established legacy series.
insert into public.ica_number_rules(issuer_id,credential_type_id,prefix,separator,next_value,digits,is_legacy_continuation)
select i.id,t.id,v.prefix,v.separator,v.next_value,v.digits,v.legacy
from (values
 ('IPMA','DAN','HQ','',8201053::bigint,7::smallint,true),
 ('WTKF','DAN','KOR','',906::bigint,5::smallint,true)
) v(issuer_code,type_code,prefix,separator,next_value,digits,legacy)
join public.ica_issuers i on i.code=v.issuer_code
join public.ica_credential_types t on t.code=v.type_code
on conflict (issuer_id,credential_type_id) do nothing;

-- New ICA pattern for every non-DAN issuer/type combination.
insert into public.ica_number_rules(issuer_id,credential_type_id,prefix,separator,next_value,digits,is_legacy_continuation)
select i.id,t.id,i.code||'-'||t.code,'-',1,6,false
from public.ica_issuers i cross join public.ica_credential_types t
where t.code <> 'DAN'
on conflict (issuer_id,credential_type_id) do nothing;

insert into public.ica_print_templates(template_code,template_kind,name,config) values
 ('ICA-CARD-V1','CARD','ICA 공통 카드 v1','{"size":"85.6x54mm","shared_back_qr":true}'::jsonb),
 ('ICA-DOCUMENT-V1','DOCUMENT','ICA A4 공식 증서 v1','{"size":"A4","orientation":"portrait"}'::jsonb)
on conflict (template_code) do nothing;

alter table public.ica_issuers enable row level security;
alter table public.ica_credential_types enable row level security;
alter table public.ica_detail_types enable row level security;
alter table public.ica_number_rules enable row level security;
alter table public.ica_credentials enable row level security;
alter table public.ica_status_history enable row level security;
alter table public.ica_reissues enable row level security;
alter table public.ica_shipments enable row level security;
alter table public.ica_print_templates enable row level security;

do $$
declare tbl text;
begin
  foreach tbl in array array['ica_issuers','ica_credential_types','ica_detail_types','ica_number_rules','ica_credentials','ica_status_history','ica_reissues','ica_shipments','ica_print_templates'] loop
    execute format('drop policy if exists %I on public.%I','ica_admin_all_'||tbl,tbl);
    execute format('create policy %I on public.%I for all to authenticated using ((select private.ica_is_admin())) with check ((select private.ica_is_admin()))','ica_admin_all_'||tbl,tbl);
  end loop;
end $$;

grant select,insert,update,delete on public.ica_issuers,public.ica_credential_types,public.ica_detail_types,
 public.ica_number_rules,public.ica_credentials,public.ica_status_history,public.ica_reissues,
 public.ica_shipments,public.ica_print_templates to authenticated;
grant usage,select on all sequences in schema public to authenticated;

create or replace function public.ica_preview_credential_no(p_issuer_code text,p_type_code text)
returns text
language plpgsql
stable
security invoker
set search_path = public, pg_temp
as $$
declare r record;
begin
  if not (select private.ica_is_admin()) then raise exception 'ICA_ADMIN_REQUIRED'; end if;
  select nr.* into r
  from public.ica_number_rules nr
  join public.ica_issuers i on i.id=nr.issuer_id
  join public.ica_credential_types t on t.id=nr.credential_type_id
  where i.code=upper(btrim(p_issuer_code)) and t.code=upper(btrim(p_type_code)) and nr.is_active;
  if not found then raise exception 'NUMBER_RULE_NOT_FOUND'; end if;
  return r.prefix||r.separator||lpad(r.next_value::text,r.digits,'0');
end;
$$;
revoke all on function public.ica_preview_credential_no(text,text) from public;
grant execute on function public.ica_preview_credential_no(text,text) to authenticated;

create or replace function public.ica_issue_credential(p_data jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_issuer public.ica_issuers%rowtype;
  v_type public.ica_credential_types%rowtype;
  v_rule public.ica_number_rules%rowtype;
  v_id uuid;
  v_no text;
begin
  if auth.uid() is null or not private.ica_is_admin() then raise exception 'ICA_ADMIN_REQUIRED'; end if;
  select * into v_issuer from public.ica_issuers where code=upper(btrim(p_data->>'issuer_code')) and is_active;
  select * into v_type from public.ica_credential_types where code=upper(btrim(p_data->>'type_code')) and is_active;
  if v_issuer.id is null or v_type.id is null then raise exception 'INVALID_ISSUER_OR_TYPE'; end if;
  if nullif(btrim(p_data->>'person_name'),'') is null then raise exception 'PERSON_NAME_REQUIRED'; end if;

  select * into v_rule from public.ica_number_rules
  where issuer_id=v_issuer.id and credential_type_id=v_type.id and is_active
  for update;
  if v_rule.id is null then raise exception 'NUMBER_RULE_NOT_FOUND'; end if;
  v_no := v_rule.prefix||v_rule.separator||lpad(v_rule.next_value::text,v_rule.digits,'0');

  insert into public.ica_credentials(
    credential_no,issuer_id,credential_type_id,detail_type_id,detail_label,person_name,person_name_en,photo_url,
    qualification_name,discipline,rank_grade,position_title,issued_on,valid_until,phone,email,postal_code,address,
    address_detail,admin_note,status,card_requested,document_requested,created_by
  ) values (
    v_no,v_issuer.id,v_type.id,nullif(p_data->>'detail_type_id','')::uuid,nullif(btrim(p_data->>'detail_label'),''),
    btrim(p_data->>'person_name'),nullif(btrim(p_data->>'person_name_en'),''),nullif(btrim(p_data->>'photo_url'),''),
    nullif(btrim(p_data->>'qualification_name'),''),nullif(btrim(p_data->>'discipline'),''),nullif(btrim(p_data->>'rank_grade'),''),
    nullif(btrim(p_data->>'position_title'),''),coalesce(nullif(p_data->>'issued_on','')::date,current_date),
    nullif(p_data->>'valid_until','')::date,nullif(btrim(p_data->>'phone'),''),nullif(btrim(p_data->>'email'),''),
    nullif(btrim(p_data->>'postal_code'),''),nullif(btrim(p_data->>'address'),''),nullif(btrim(p_data->>'address_detail'),''),
    nullif(btrim(p_data->>'admin_note'),''),'VALID',coalesce((p_data->>'card_requested')::boolean,v_type.default_card),
    coalesce((p_data->>'document_requested')::boolean,v_type.default_document),auth.uid()
  ) returning id into v_id;

  update public.ica_number_rules set next_value=next_value+1,updated_at=now() where id=v_rule.id;
  insert into public.ica_status_history(credential_id,old_status,new_status,reason,changed_by)
  values(v_id,null,'VALID','INITIAL_ISSUE',auth.uid());
  return jsonb_build_object('id',v_id,'credential_no',v_no);
end;
$$;
revoke all on function public.ica_issue_credential(jsonb) from public;
grant execute on function public.ica_issue_credential(jsonb) to authenticated;

create or replace function public.ica_change_status(p_credential_id uuid,p_new_status text,p_reason text default null)
returns void
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare old_value text; new_value text:=upper(btrim(p_new_status));
begin
  if auth.uid() is null or not private.ica_is_admin() then raise exception 'ICA_ADMIN_REQUIRED'; end if;
  if new_value not in ('VALID','EXPIRED','SUSPENDED','REVOKED') then raise exception 'INVALID_STATUS'; end if;
  select status into old_value from public.ica_credentials where id=p_credential_id for update;
  if old_value is null then raise exception 'CREDENTIAL_NOT_FOUND'; end if;
  update public.ica_credentials set status=new_value,updated_at=now() where id=p_credential_id;
  insert into public.ica_status_history(credential_id,old_status,new_status,reason,changed_by)
  values(p_credential_id,old_value,new_value,nullif(btrim(p_reason),''),auth.uid());
end;
$$;
revoke all on function public.ica_change_status(uuid,text,text) from public;
grant execute on function public.ica_change_status(uuid,text,text) to authenticated;

create or replace function public.ica_record_reissue(p_credential_id uuid,p_reason text)
returns bigint
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare v_id bigint;
begin
  if auth.uid() is null or not private.ica_is_admin() then raise exception 'ICA_ADMIN_REQUIRED'; end if;
  if not exists(select 1 from public.ica_credentials where id=p_credential_id) then raise exception 'CREDENTIAL_NOT_FOUND'; end if;
  insert into public.ica_reissues(credential_id,reason,processed_by) values(p_credential_id,btrim(p_reason),auth.uid()) returning id into v_id;
  return v_id;
end;
$$;
revoke all on function public.ica_record_reissue(uuid,text) from public;
grant execute on function public.ica_record_reissue(uuid,text) to authenticated;

create or replace function public.ica_verify_credential(p_credential_no text)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare q text:=upper(btrim(p_credential_no)); result jsonb;
begin
  if q='' then return null; end if;
  select jsonb_build_object(
    'source','ICA','status',c.status,'credential_no',c.credential_no,'person_name',c.person_name,
    'person_name_en',c.person_name_en,'issuer_code',i.code,'issuer_name',i.name_ko,'issuer_name_en',i.name_en,
    'type_code',t.code,'type_name',t.name_ko,'detail_name',coalesce(d.name_ko,c.detail_label),
    'qualification_name',c.qualification_name,'discipline',c.discipline,'rank_grade',c.rank_grade,
    'position_title',c.position_title,'issued_on',c.issued_on,'valid_until',c.valid_until,
    'verified_by','ICA'
  ) into result
  from public.ica_credentials c join public.ica_issuers i on i.id=c.issuer_id
  join public.ica_credential_types t on t.id=c.credential_type_id
  left join public.ica_detail_types d on d.id=c.detail_type_id
  where upper(c.credential_no)=q;
  if result is not null then return result; end if;

  select jsonb_build_object(
    'source','LEGACY','status','VALID','credential_no',l.certificate_no,'person_name',l.name,'person_name_en',l.name_en,
    'issuer_code',l.organization_code,
    'issuer_name',case when l.organization_code='WTKF' then '세계태권검도연맹' else '국제경찰무도연합회' end,
    'type_code','DAN',
    'type_name',case when l.organization_code='WTKF' then '태권검도 단증' when l.certificate_no ilike '%경호무술%' then '경호무술 단증' else '경찰무도 단증' end,
    'rank_grade',case when l.rank_no is null then null else l.rank_no::text||'단' end,
    'issued_on',l.issued_at,'valid_until',null,'verified_by','ICA'
  ) into result
  from public.gms_legacy_members l where upper(btrim(l.certificate_no))=q limit 1;
  return result;
end;
$$;
revoke all on function public.ica_verify_credential(text) from public;
grant execute on function public.ica_verify_credential(text) to anon,authenticated;

notify pgrst, 'reload schema';
